import type { Theme } from '@react-navigation/native';
import { I18nManager, StyleSheet } from 'react-native';

import {
  fontSize,
  fontWeight,
  FORM_CONTROL_HEIGHT,
  radius,
  spacing,
} from '@/ui/theme';
import { hexAlpha } from '@/ui/theme/utils/colorUtils';

export function createTicketScreenStyles(colors: Theme['colors']) {
  return StyleSheet.create({
        scrollContent: {
          paddingHorizontal: spacing.xl,
          paddingBottom: spacing['4xl'],
          gap: spacing.md,
        },
        notice: {
          fontSize: fontSize.sm,
          color: colors.text,
          opacity: 0.85,
          lineHeight: fontSize.sm * 1.5,
          marginBottom: spacing.sm,
          textAlign: I18nManager.isRTL ? 'left' : 'right',
          writingDirection: 'rtl',
        },
        headerRow: {
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: spacing.md,
          marginBottom: spacing.sm,
        },
        listWrap: {
          minHeight: 120,
        },
        listFill: {
          flex: 1,
        },
        ticketCardOuter: {
          marginBottom: spacing.sm,
        },
        ticketCard: {
          padding: spacing.md,
          borderRadius: radius.md,
          borderWidth: StyleSheet.hairlineWidth,
          borderColor: colors.border,
          backgroundColor: colors.card,
          gap: spacing.sm,
          width: '100%',
        },
        ticketCardHeaderRow: {
          flexDirection: 'row',
          alignItems: 'flex-start',
          justifyContent: 'space-between',
          gap: spacing.md,
          width: '100%',
        },
        ticketCardTitleText: {
          flex: 1,
          minWidth: 0,
          fontSize: fontSize.base,
          fontWeight: fontWeight.semibold,
          color: colors.text,
          textAlign: 'right',
          writingDirection: 'rtl',
        },
        ticketStatusBadge: {
          flexShrink: 0,
          maxWidth: '46%',
          paddingVertical: spacing.xs,
          paddingHorizontal: spacing.sm,
          borderRadius: radius.sm,
          backgroundColor: hexAlpha(colors.primary, 0.14),
        },
        ticketStatusBadgeText: {
          fontSize: fontSize.sm,
          fontWeight: fontWeight.semibold,
          color: colors.primary,
          textAlign: 'center',
        },
        ticketCardFields: {
          gap: spacing.sm,
          width: '100%',
        },
        ticketLabelValueRow: {
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'space-between',
          width: '100%',
          gap: spacing.md,
        },
        ticketLabelValueLabel: {
          fontSize: fontSize.sm,
          fontWeight: fontWeight.medium,
          color: colors.text,
          opacity: 0.62,
          flexShrink: 0,
          maxWidth: '46%',
        },
        ticketLabelValueValue: {
          flex: 1,
          fontSize: fontSize.sm,
          color: colors.text,
          textAlign: 'right',
          writingDirection: 'ltr',
        },
        ticketCardViewButton: {
          marginTop: spacing.sm,
          width: '100%',
          alignSelf: 'stretch',
          paddingVertical: spacing.md,
          paddingHorizontal: spacing.md,
          borderRadius: radius.md,
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: colors.primary,
        },
        ticketCardViewButtonPressed: {
          opacity: 0.88,
        },
        ticketCardViewButtonLabel: {
          fontSize: fontSize.base,
          fontWeight: fontWeight.bold,
          color: colors.background,
        },
        ticketTitle: {
          fontSize: fontSize.base,
          fontWeight: fontWeight.semibold,
          color: colors.text,
          textAlign: 'right',
          writingDirection: 'rtl',
        },
        ticketMeta: {
          fontSize: fontSize.sm,
          color: colors.text,
          opacity: 0.65,
          textAlign: 'right',
          writingDirection: 'rtl',
        },
        modalSurface: {
          marginHorizontal: spacing.md,
          marginTop: spacing['2xl'],
          padding: spacing.xl,
          borderRadius: radius.lg,
          backgroundColor: colors.card,
          borderWidth: StyleSheet.hairlineWidth,
          borderColor: colors.border,
          gap: spacing.md,
        },
        label: {
          fontSize: fontSize.sm,
          fontWeight: fontWeight.semibold,
          color: colors.text,
          marginBottom: spacing.xs,
          textAlign: 'right',
          writingDirection: 'rtl',
        },
        input: {
          borderWidth: StyleSheet.hairlineWidth,
          borderColor: colors.border,
          borderRadius: radius.sm,
          paddingHorizontal: spacing.md,
          paddingVertical: 0,
          height: FORM_CONTROL_HEIGHT,
          fontSize: fontSize.base,
          color: colors.text,
          backgroundColor: colors.background,
          textAlign: 'right',
          writingDirection: 'rtl',
        },
        multiline: {
          height: 120,
          minHeight: 120,
          paddingTop: spacing.md,
          paddingBottom: spacing.md,
          textAlignVertical: 'top',
        },
        submitBtn: {
          marginTop: spacing.sm,
          height: FORM_CONTROL_HEIGHT,
          borderRadius: radius.md,
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: colors.primary,
        },
        submitLabel: {
          fontSize: fontSize.base,
          fontWeight: fontWeight.bold,
          color: colors.background,
          textAlign: 'center',
        },
        submitDisabled: {
          opacity: 0.45,
        },
        submitBtnSlot: {
          flex: 1,
          width: '100%',
          alignItems: 'center',
          justifyContent: 'center',
        },
        submitLabelHidden: { opacity: 0 },
        submitLoaderOverlay: {
          ...StyleSheet.absoluteFill,
          alignItems: 'center',
          justifyContent: 'center',
        },
        bubbleRow: {
          gap: spacing.sm,
          paddingVertical: spacing.sm,
          borderBottomWidth: StyleSheet.hairlineWidth,
          borderBottomColor: colors.border,
        },
        bubbleAuthor: {
          fontSize: fontSize.sm,
          fontWeight: fontWeight.semibold,
          color: colors.text,
          textAlign: 'right',
          writingDirection: 'rtl',
        },
        bubbleBody: {
          fontSize: fontSize.base,
          color: colors.text,
          lineHeight: fontSize.base * 1.45,
          textAlign: 'right',
          writingDirection: 'rtl',
        },
        bubbleTime: {
          fontSize: fontSize.sm - 1,
          color: colors.text,
          opacity: 0.55,
          textAlign: 'right',
        },
        replyRow: {
          gap: spacing.sm,
          marginTop: spacing.md,
        },
        attachmentSection: {
          gap: spacing.sm,
          marginTop: spacing.sm,
        },
        attachmentPicker: {
          width: '100%',
          borderRadius: radius.sm,
          borderStyle: 'dashed',
          borderColor: colors.primary,
          backgroundColor: hexAlpha(colors.primary, 0.08),
        },
        attachmentHint: {
          fontSize: fontSize.sm - 1,
          color: colors.text,
          opacity: 0.62,
          textAlign: 'right',
          writingDirection: 'rtl',
        },
        attachmentRow: {
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: spacing.sm,
          paddingVertical: spacing.xs,
          borderBottomWidth: StyleSheet.hairlineWidth,
          borderBottomColor: colors.border,
        },
        attachmentName: {
          flex: 1,
          fontSize: fontSize.sm,
          color: colors.text,
          textAlign: 'right',
        },
        attachmentRemove: {
          paddingHorizontal: spacing.sm,
          minWidth: 56,
        },
        remoteAttachmentList: {
          gap: spacing.xs,
          marginTop: spacing.xs,
        },
        remoteAttachmentButton: {
          alignSelf: 'flex-end',
          paddingHorizontal: 0,
        },
        createTicketLink: {
          paddingVertical: spacing.sm,
          paddingHorizontal: spacing.md,
        },
        createTicketLinkText: {
          fontSize: fontSize.sm,
          fontWeight: fontWeight.bold,
          color: colors.primary,
        },
        listFooterSpinner: {
          paddingVertical: spacing.md,
          alignItems: 'center',
        },
        retryLink: {
          marginTop: spacing.md,
          paddingHorizontal: spacing.md,
          paddingVertical: spacing.sm,
        },
        retryLinkLabel: {
          fontSize: fontSize.base,
          fontWeight: fontWeight.semibold,
          color: colors.primary,
        },
      });
}

export type TicketScreenStyles = ReturnType<typeof createTicketScreenStyles>;
