import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/ui/theme';

export function createWelcomeGuideStyles(c: ThemeColors) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.overlay,
    },
    card: {
      backgroundColor: c.surface,
      borderColor: c.border,
      borderWidth: 1,
      borderRadius: 28,
      overflow: 'hidden',
    },
    topLine: { height: 3, backgroundColor: c.primary },
    header: {
      minHeight: 62,
      paddingHorizontal: 20,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    brand: { flexDirection: 'row', gap: 7, alignItems: 'center' },
    brandDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: c.primary,
    },
    brandText: { fontSize: 12, fontWeight: '600', color: c.textSecondary },
    skip: {
      minHeight: 44,
      minWidth: 48,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 4,
    },
    skipText: { fontSize: 13, color: c.textMuted },
    viewport: { flex: 1, direction: 'ltr' },
    carousel: { direction: 'ltr' },
    slide: { flex: 1 },
    slideContent: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 22,
      paddingBottom: 8,
      gap: 12,
    },
    artwork: { width: '100%', maxWidth: 320, aspectRatio: 4 / 3 },
    tag: {
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 20,
      backgroundColor: c.primarySoft,
    },
    tagText: {
      fontSize: 11,
      lineHeight: 20,
      color: c.textSecondary,
      fontWeight: '600',
      textAlign: 'center',
    },
    title: {
      fontSize: 25,
      lineHeight: 39,
      fontWeight: '700',
      color: c.text,
      textAlign: 'center',
    },
    description: {
      fontSize: 14,
      lineHeight: 27,
      color: c.textSecondary,
      textAlign: 'center',
    },
    hint: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 12,
      backgroundColor: c.surfaceSecondary,
      alignSelf: 'stretch',
    },
    hintText: {
      flexShrink: 1,
      fontSize: 11,
      lineHeight: 21,
      color: c.textSecondary,
      textAlign: 'center',
    },
    footer: { paddingHorizontal: 22, paddingTop: 4, paddingBottom: 18, gap: 8 },
    pagination: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    dots: { flexDirection: 'row', alignItems: 'center' },
    dotTarget: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dot: { height: 6, width: 6, borderRadius: 3, backgroundColor: c.border },
    activeDot: { width: 22, backgroundColor: c.primary },
    counter: { fontSize: 12, color: c.textMuted },
    actions: { flexDirection: 'row', gap: 10 },
    next: {
      flex: 1,
      minHeight: 52,
      borderRadius: 15,
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: c.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    nextText: {
      fontSize: 15,
      fontWeight: '700',
      color: c.onPrimary,
      textAlign: 'center',
    },
    previous: {
      minWidth: 68,
      minHeight: 52,
      borderRadius: 15,
      borderColor: c.border,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 10,
    },
    previousText: { fontSize: 13, color: c.textSecondary },
    swipeHint: {
      fontSize: 10,
      lineHeight: 18,
      color: c.textMuted,
      textAlign: 'center',
    },
    pressed: { opacity: 0.7 },
  });
}
